"use strict";
// Generated from the sibling ESM source by scripts/build_shared_cjs.cjs.
// Do not edit this file directly; run `pnpm build:shared-cjs` from the repo root.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/shared/rules-engine/predefinedRules.js
var predefinedRules_exports = {};
__export(predefinedRules_exports, {
  PREDEFINED_RULES: () => PREDEFINED_RULES,
  findPredefinedRule: () => findPredefinedRule,
  listPredefinedRules: () => listPredefinedRules
});
module.exports = __toCommonJS(predefinedRules_exports);
var PREDEFINED_RULES = [
  {
    id: "price_crosses_ema",
    abbr: "PX_EMA",
    name: "Price Crosses EMA",
    icon: "crosshair",
    family: "moving_average",
    params: { side: "above", source: "close", ema_length: 20 },
    condition: {
      crosses_above: [{ var: "bar.close" }, { var: "indicators.ema_20" }]
    },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "ema_fast_crosses_ema_slow",
    abbr: "EMA_X",
    name: "Fast EMA Crosses Slow EMA",
    icon: "git-compare-arrows",
    family: "moving_average",
    params: { side: "above", fast_length: 9, slow_length: 21 },
    condition: {
      crosses_above: [{ var: "indicators.ema_fast" }, { var: "indicators.ema_slow" }]
    },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "price_rejected_ema",
    abbr: "RJ_EMA",
    name: "Price Rejected EMA",
    icon: "undo-2",
    family: "moving_average",
    params: { ema_length: 20 },
    condition: {
      rejected: [{ var: "bar.close" }, { var: "indicators.ema_20" }]
    },
    outputs: { marker: "dot" }
  },
  {
    id: "price_crosses_vwap",
    abbr: "PX_VWAP",
    name: "Price Crosses VWAP",
    icon: "waves",
    family: "vwap",
    params: { side: "above" },
    condition: {
      crosses_above: [{ var: "bar.close" }, { var: "indicators.vwap" }]
    },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "price_rejected_key_level",
    abbr: "RJ_LVL",
    name: "Price Rejected Key Level",
    icon: "minus",
    family: "key_level",
    params: { level: "levels.key" },
    condition: {
      rejected: [{ var: "bar.close" }, { var: "levels.key" }]
    },
    outputs: { marker: "dot" }
  },
  {
    id: "price_breaks_key_level",
    abbr: "BRK_LVL",
    name: "Price Breaks Key Level",
    icon: "move-up-right",
    family: "key_level",
    params: { side: "above", close_confirmation: true },
    condition: {
      crosses_above: [{ var: "bar.close" }, { var: "levels.key" }]
    },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "price_rejected_bollinger_band",
    abbr: "RJ_BB",
    name: "Price Rejected Bollinger Band",
    icon: "brackets",
    family: "volatility",
    params: { band: "lower" },
    condition: {
      rejected: [{ var: "bar.close" }, { var: "indicators.bb_lower" }]
    },
    outputs: { marker: "dot" }
  },
  {
    id: "macd_cross",
    abbr: "MACD_X",
    name: "MACD Cross",
    icon: "chart-no-axes-combined",
    family: "momentum",
    params: { side: "above" },
    condition: {
      crosses_above: [{ var: "indicators.macd" }, { var: "indicators.macd_signal" }]
    },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "bullish_engulfing",
    abbr: "B_ENG",
    name: "Bullish Engulfing",
    icon: "candlestick-chart",
    family: "candle_pattern",
    params: {},
    condition: { fn: "engulfing", args: ["bullish"] },
    outputs: { bias: "bullish", marker: "arrow_up" }
  },
  {
    id: "bearish_engulfing",
    abbr: "S_ENG",
    name: "Bearish Engulfing",
    icon: "candlestick-chart",
    family: "candle_pattern",
    params: {},
    condition: { fn: "engulfing", args: ["bearish"] },
    outputs: { bias: "bearish", marker: "arrow_down" }
  },
  {
    id: "liquidity_sweep",
    abbr: "SWP",
    name: "Liquidity Sweep",
    icon: "scan-line",
    family: "structure",
    params: { bias: "" },
    condition: { fn: "sweep", args: [] },
    outputs: { marker: "diamond" }
  },
  {
    id: "break_of_structure",
    abbr: "BOS",
    name: "Break of Structure",
    icon: "route",
    family: "structure",
    params: { bias: "" },
    condition: { fn: "bos", args: [] },
    outputs: { marker: "flag" }
  },
  {
    id: "change_of_character",
    abbr: "CHOCH",
    name: "Change of Character",
    icon: "shuffle",
    family: "structure",
    params: { bias: "" },
    condition: { fn: "choch", args: [] },
    outputs: { marker: "flag" }
  }
];
function listPredefinedRules() {
  return PREDEFINED_RULES.map((rule) => ({
    ...rule,
    params: { ...rule.params || {} },
    outputs: { ...rule.outputs || {} },
    condition: JSON.parse(JSON.stringify(rule.condition || null))
  }));
}
function findPredefinedRule(id = "") {
  const needle = String(id || "").trim();
  return listPredefinedRules().find((rule) => rule.id === needle) || null;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  PREDEFINED_RULES,
  findPredefinedRule,
  listPredefinedRules
});
