const { sqliteTable, text, integer, real } = require("drizzle-orm/sqlite-core");

const users = sqliteTable("users", {
  userId: text("user_id").primaryKey(),
  name: text("name"),
  email: text("email"),
  passwordHash: text("password_hash"),
  passwordSalt: text("password_salt"),
  roles: text("roles"),
  permissions: text("permissions"),
  isActive: integer("is_active"),
  metadata: text("metadata"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const trades = sqliteTable("trades", {
  sid: text("sid").primaryKey(),
  accountId: text("account_id").notNull(),
  userId: text("user_id").notNull(),
  tradeId: text("trade_id"),
  sourceId: text("source_id"),
  strategy: text("strategy"),
  entryModel: text("entry_model"),
  tradeTf: text("trade_tf"),
  chartTf: text("chart_tf"),
  symbol: text("symbol").notNull(),
  action: text("action").notNull(),
  orderType: text("order_type"),
  volume: real("volume"),
  entry: real("entry"),
  sl: real("sl"),
  tp: real("tp"),
  tp1: real("tp1"),
  tp2: real("tp2"),
  tp3: real("tp3"),
  rrPlanned: real("rr_planned"),
  riskPctPlanned: real("risk_pct_planned"),
  riskMoneyPlanned: real("risk_money_planned"),
  confidencePct: real("confidence_pct"),
  estimatedBars: integer("estimated_bars"),
  beTrigger: real("be_trigger"),
  profile: text("profile"),
  invalidation: text("invalidation"),
  entryCondition: text("entry_condition"),
  exitCondition: text("exit_condition"),
  confluenceChecklist: text("confluence_checklist"),
  skipRecommendation: text("skip_recommendation"),
  riskManagement: text("risk_management"),
  note: text("note"),
  leaseToken: text("lease_token"),
  leaseExpiresAt: text("lease_expires_at"),
  dispatchStatus: text("dispatch_status").notNull(),
  executionStatus: text("execution_status").notNull(),
  closeReason: text("close_reason"),
  rejectionReason: text("rejection_reason"),
  brokerTradeId: text("broker_trade_id"),
  entryExec: real("entry_exec"),
  brokerPips: real("broker_pips"),
  brokerLots: real("broker_lots"),
  brokerCommission: real("broker_commission"),
  brokerSwap: real("broker_swap"),
  brokerVolume: real("broker_volume"),
  brokerPnl: real("broker_pnl"),
  brokerMargin: real("broker_margin"),
  plannedTpPnl: real("planned_tp_pnl"),
  plannedSlPnl: real("planned_sl_pnl"),
  brokerTpPnl: real("broker_tp_pnl"),
  brokerSlPnl: real("broker_sl_pnl"),
  openedAt: text("opened_at"),
  closedAt: text("closed_at"),
  pnlRealized: real("pnl_realized"),
  metadata: text("metadata"),
  rawJson: text("raw_json"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

module.exports = {
  users,
  trades,
};
