const {
  pgTable,
  text,
  integer,
  doublePrecision,
  numeric,
  boolean,
  timestamp,
} = require("drizzle-orm/pg-core");

const users = pgTable("users", {
  userId: text("user_id").primaryKey(),
  name: text("name"),
  email: text("email").unique(),
  passwordHash: text("password_hash"),
  passwordSalt: text("password_salt"),
  roles: text("roles"),
  permissions: text("permissions"),
  isActive: boolean("is_active").default(true),
  metadata: text("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

const trades = pgTable("trades", {
  sid: text("sid").primaryKey(),
  accountId: text("account_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => users.userId, { onDelete: "cascade" }),
  tradeId: text("trade_id"),
  sourceId: text("source_id"),
  strategy: text("strategy"),
  entryModel: text("entry_model"),
  tradeTf: text("trade_tf"),
  chartTf: text("chart_tf"),
  symbol: text("symbol").notNull(),
  action: text("action").notNull(),
  orderType: text("order_type"),
  volume: doublePrecision("volume"),
  entry: doublePrecision("entry"),
  sl: doublePrecision("sl"),
  tp: doublePrecision("tp"),
  tp1: doublePrecision("tp1"),
  tp2: doublePrecision("tp2"),
  tp3: doublePrecision("tp3"),
  rrPlanned: doublePrecision("rr_planned"),
  riskPctPlanned: doublePrecision("risk_pct_planned"),
  riskMoneyPlanned: doublePrecision("risk_money_planned"),
  confidencePct: doublePrecision("confidence_pct"),
  estimatedBars: integer("estimated_bars"),
  beTrigger: doublePrecision("be_trigger"),
  profile: text("profile"),
  invalidation: text("invalidation"),
  entryCondition: text("entry_condition"),
  exitCondition: text("exit_condition"),
  confluenceChecklist: text("confluence_checklist"),
  skipRecommendation: text("skip_recommendation"),
  riskManagement: text("risk_management"),
  note: text("note"),
  leaseToken: text("lease_token"),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  dispatchStatus: text("dispatch_status").notNull().default("NEW"),
  executionStatus: text("execution_status").notNull().default("PENDING"),
  closeReason: text("close_reason"),
  rejectionReason: text("rejection_reason"),
  brokerTradeId: text("broker_trade_id"),
  entryExec: doublePrecision("entry_exec"),
  brokerPips: doublePrecision("broker_pips"),
  brokerLots: doublePrecision("broker_lots"),
  brokerCommission: doublePrecision("broker_commission"),
  brokerSwap: doublePrecision("broker_swap"),
  brokerVolume: doublePrecision("broker_volume"),
  brokerPnl: doublePrecision("broker_pnl"),
  brokerMargin: doublePrecision("broker_margin"),
  plannedTpPnl: doublePrecision("planned_tp_pnl"),
  plannedSlPnl: doublePrecision("planned_sl_pnl"),
  brokerTpPnl: doublePrecision("broker_tp_pnl"),
  brokerSlPnl: doublePrecision("broker_sl_pnl"),
  openedAt: timestamp("opened_at", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  pnlRealized: doublePrecision("pnl_realized"),
  metadata: text("metadata"),
  rawJson: text("raw_json"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

const objectEntities = pgTable("object_entities", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  entityType: text("entity_type").notNull(),
  entityKey: text("entity_key").notNull(),
  parentId: text("parent_id"),
  derivedFromId: text("derived_from_id"),
  userId: text("user_id"),
  ownerId: text("owner_id"),
  ownerTeamId: text("owner_team_id"),
  slug: text("slug"),
  title: text("title"),
  subtitle: text("subtitle"),
  status: text("status").notNull(),
  state: text("state"),
  category: text("category"),
  subtype: text("subtype"),
  priority: integer("priority").notNull(),
  visibility: text("visibility").notNull(),
  accessLevel: text("access_level").notNull(),
  scopeType: text("scope_type").notNull(),
  scopeTenantId: text("scope_tenant_id"),
  scopeModule: text("scope_module"),
  scopeUserId: text("scope_user_id"),
  lang: text("lang").notNull(),
  locale: text("locale").notNull(),
  countryCode: text("country_code"),
  sortOrder: integer("sort_order").notNull(),
  currency: text("currency"),
  amount: numeric("amount"),
  quantity: doublePrecision("quantity"),
  price: numeric("price"),
  balance: numeric("balance"),
  imageUrl: text("image_url"),
  icon: text("icon"),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  syncStatus: text("sync_status"),
  versionNo: integer("version_no").notNull(),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  effectiveFrom: timestamp("effective_from", { withTimezone: true }),
  effectiveTo: timestamp("effective_to", { withTimezone: true }),
  startAt: timestamp("start_at", { withTimezone: true }),
  endAt: timestamp("end_at", { withTimezone: true }),
  dueAt: timestamp("due_at", { withTimezone: true }),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  searchText: text("search_text"),
  meta: text("meta"),
  data: text("data").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

const objectLinks = pgTable("object_links", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  fromEntityId: text("from_entity_id").notNull(),
  toEntityId: text("to_entity_id").notNull(),
  fromType: text("from_type"),
  toType: text("to_type"),
  linkType: text("link_type").notNull(),
  userId: text("user_id"),
  sortOrder: integer("sort_order").notNull(),
  status: text("status").notNull(),
  data: text("data").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

const objectJournal = pgTable("object_journal", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  entityId: text("entity_id"),
  entityType: text("entity_type"),
  entityKey: text("entity_key"),
  userId: text("user_id"),
  entryType: text("entry_type").notNull(),
  direction: text("direction"),
  amount: numeric("amount"),
  currency: text("currency"),
  happenedAt: timestamp("happened_at", { withTimezone: true }).defaultNow(),
  sortOrder: integer("sort_order").notNull(),
  data: text("data").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

const objectProcesses = pgTable("object_processes", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  processType: text("process_type").notNull(),
  topic: text("topic").notNull(),
  entityId: text("entity_id"),
  entityType: text("entity_type"),
  entityKey: text("entity_key"),
  userId: text("user_id"),
  status: text("status").notNull(),
  priority: integer("priority").notNull(),
  attemptCount: integer("attempt_count").notNull(),
  maxAttempts: integer("max_attempts").notNull(),
  runAt: timestamp("run_at", { withTimezone: true }).defaultNow(),
  lockedAt: timestamp("locked_at", { withTimezone: true }),
  lockedBy: text("locked_by"),
  lastError: text("last_error"),
  payload: text("payload").notNull(),
  result: text("result").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

module.exports = {
  users,
  trades,
  objectEntities,
  objectLinks,
  objectJournal,
  objectProcesses,
};
