const { sqliteTable, text, integer, real } = require("drizzle-orm/sqlite-core");

const users = sqliteTable("users", {
  userId: text("user_id").primaryKey(),
  name: text("name"),
  email: text("email"),
  passwordHash: text("password_hash"),
  passwordSalt: text("password_salt"),
  roles: text("roles"),
  permissions: text("permissions"),
  isActive: integer("is_active"),
  metadata: text("metadata"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const trades = sqliteTable("trades", {
  sid: text("sid").primaryKey(),
  accountId: text("account_id").notNull(),
  userId: text("user_id").notNull(),
  tradeId: text("trade_id"),
  sourceId: text("source_id"),
  strategy: text("strategy"),
  entryModel: text("entry_model"),
  tradeTf: text("trade_tf"),
  chartTf: text("chart_tf"),
  symbol: text("symbol").notNull(),
  action: text("action").notNull(),
  orderType: text("order_type"),
  volume: real("volume"),
  entry: real("entry"),
  sl: real("sl"),
  tp: real("tp"),
  tp1: real("tp1"),
  tp2: real("tp2"),
  tp3: real("tp3"),
  rrPlanned: real("rr_planned"),
  riskPctPlanned: real("risk_pct_planned"),
  riskMoneyPlanned: real("risk_money_planned"),
  confidencePct: real("confidence_pct"),
  estimatedBars: integer("estimated_bars"),
  beTrigger: real("be_trigger"),
  profile: text("profile"),
  invalidation: text("invalidation"),
  entryCondition: text("entry_condition"),
  exitCondition: text("exit_condition"),
  confluenceChecklist: text("confluence_checklist"),
  skipRecommendation: text("skip_recommendation"),
  riskManagement: text("risk_management"),
  note: text("note"),
  leaseToken: text("lease_token"),
  leaseExpiresAt: text("lease_expires_at"),
  dispatchStatus: text("dispatch_status").notNull(),
  executionStatus: text("execution_status").notNull(),
  closeReason: text("close_reason"),
  rejectionReason: text("rejection_reason"),
  brokerTradeId: text("broker_trade_id"),
  entryExec: real("entry_exec"),
  brokerPips: real("broker_pips"),
  brokerLots: real("broker_lots"),
  brokerCommission: real("broker_commission"),
  brokerSwap: real("broker_swap"),
  brokerVolume: real("broker_volume"),
  brokerPnl: real("broker_pnl"),
  brokerMargin: real("broker_margin"),
  plannedTpPnl: real("planned_tp_pnl"),
  plannedSlPnl: real("planned_sl_pnl"),
  brokerTpPnl: real("broker_tp_pnl"),
  brokerSlPnl: real("broker_sl_pnl"),
  openedAt: text("opened_at"),
  closedAt: text("closed_at"),
  pnlRealized: real("pnl_realized"),
  metadata: text("metadata"),
  rawJson: text("raw_json"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

const objectEntities = sqliteTable("object_entities", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  entityType: text("entity_type").notNull(),
  entityKey: text("entity_key").notNull(),
  parentId: text("parent_id"),
  derivedFromId: text("derived_from_id"),
  userId: text("user_id"),
  ownerId: text("owner_id"),
  ownerTeamId: text("owner_team_id"),
  slug: text("slug"),
  title: text("title"),
  subtitle: text("subtitle"),
  status: text("status").notNull(),
  state: text("state"),
  category: text("category"),
  subtype: text("subtype"),
  priority: integer("priority").notNull(),
  visibility: text("visibility").notNull(),
  accessLevel: text("access_level").notNull(),
  scopeType: text("scope_type").notNull(),
  scopeTenantId: text("scope_tenant_id"),
  scopeModule: text("scope_module"),
  scopeUserId: text("scope_user_id"),
  lang: text("lang").notNull(),
  locale: text("locale").notNull(),
  countryCode: text("country_code"),
  sortOrder: integer("sort_order").notNull(),
  currency: text("currency"),
  amount: real("amount"),
  quantity: real("quantity"),
  price: real("price"),
  balance: real("balance"),
  imageUrl: text("image_url"),
  icon: text("icon"),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  syncStatus: text("sync_status"),
  versionNo: integer("version_no").notNull(),
  publishedAt: text("published_at"),
  archivedAt: text("archived_at"),
  effectiveFrom: text("effective_from"),
  effectiveTo: text("effective_to"),
  startAt: text("start_at"),
  endAt: text("end_at"),
  dueAt: text("due_at"),
  scheduledAt: text("scheduled_at"),
  searchText: text("search_text"),
  meta: text("meta"),
  data: text("data").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

const objectLinks = sqliteTable("object_links", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  fromEntityId: text("from_entity_id").notNull(),
  toEntityId: text("to_entity_id").notNull(),
  fromType: text("from_type"),
  toType: text("to_type"),
  linkType: text("link_type").notNull(),
  userId: text("user_id"),
  sortOrder: integer("sort_order").notNull(),
  status: text("status").notNull(),
  data: text("data").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

const objectJournal = sqliteTable("object_journal", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  entityId: text("entity_id"),
  entityType: text("entity_type"),
  entityKey: text("entity_key"),
  userId: text("user_id"),
  entryType: text("entry_type").notNull(),
  direction: text("direction"),
  amount: real("amount"),
  currency: text("currency"),
  happenedAt: text("happened_at").notNull(),
  sortOrder: integer("sort_order").notNull(),
  data: text("data").notNull(),
  createdAt: text("created_at").notNull(),
});

const objectProcesses = sqliteTable("object_processes", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  processType: text("process_type").notNull(),
  topic: text("topic").notNull(),
  entityId: text("entity_id"),
  entityType: text("entity_type"),
  entityKey: text("entity_key"),
  userId: text("user_id"),
  status: text("status").notNull(),
  priority: integer("priority").notNull(),
  attemptCount: integer("attempt_count").notNull(),
  maxAttempts: integer("max_attempts").notNull(),
  runAt: text("run_at").notNull(),
  lockedAt: text("locked_at"),
  lockedBy: text("locked_by"),
  lastError: text("last_error"),
  payload: text("payload").notNull(),
  result: text("result").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

module.exports = {
  users,
  trades,
  objectEntities,
  objectLinks,
  objectJournal,
  objectProcesses,
};
