#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DB_MANAGER_DIR="${REPO_DIR}/src/apps/db-manager"
LOCAL_DIR="${REPO_DIR}/src/apps/.local/db-manager"
CONFIG_PATH="${LOCAL_DIR}/connections.json"
PID_PATH="${LOCAL_DIR}/db-manager.pid"
LOG_PATH="${LOCAL_DIR}/db-manager.log"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-mt5_bridge_local}"
DB_USER="${DB_USER:-$(id -un)}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_MANAGER_HOST="${DB_MANAGER_HOST:-127.0.0.1}"
DB_MANAGER_PORT="${DB_MANAGER_PORT:-8088}"

mkdir -p "${LOCAL_DIR}"

log() {
  printf '[start_db] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "Missing required command: $1"
    exit 1
  fi
}

choose_postgres_formula() {
  if ! command -v brew >/dev/null 2>&1; then
    return 1
  fi
  local running
  running="$(brew services list 2>/dev/null | awk '/^postgresql(@[0-9]+)?[[:space:]]/ { print $1; exit }')"
  if [[ -n "${running}" ]]; then
    printf '%s\n' "${running}"
    return 0
  fi
  local installed
  installed="$(brew list --formula 2>/dev/null | awk '/^postgresql(@[0-9]+)?$/ { print; exit }')"
  if [[ -n "${installed}" ]]; then
    printf '%s\n' "${installed}"
    return 0
  fi
  return 1
}

wait_for_postgres() {
  local attempts=20
  while (( attempts > 0 )); do
    if pg_isready -h "${DB_HOST}" -p "${DB_PORT}" >/dev/null 2>&1; then
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done
  return 1
}

ensure_postgres() {
  require_cmd pg_isready
  if pg_isready -h "${DB_HOST}" -p "${DB_PORT}" >/dev/null 2>&1; then
    log "Postgres already reachable at ${DB_HOST}:${DB_PORT}"
    return 0
  fi

  if ! command -v brew >/dev/null 2>&1; then
    log "Postgres is not reachable and Homebrew is unavailable."
    exit 1
  fi

  local formula
  formula="$(choose_postgres_formula || true)"
  if [[ -z "${formula}" ]]; then
    log "Could not find an installed Homebrew PostgreSQL formula."
    exit 1
  fi

  log "Starting Homebrew service: ${formula}"
  brew services start "${formula}" >/dev/null

  if ! wait_for_postgres; then
    log "Postgres did not become ready on ${DB_HOST}:${DB_PORT}"
    exit 1
  fi
  log "Postgres is ready at ${DB_HOST}:${DB_PORT}"
}

write_manager_config() {
  local conn
  if [[ -n "${DB_PASSWORD}" ]]; then
    conn="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  else
    conn="postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  fi

  cat > "${CONFIG_PATH}" <<EOF
{
  "connections": [
    {
      "id": "mt5_bridge_local",
      "name": "MT5 Local mt5_bridge_local",
      "connectionString": "${conn}",
      "note": "Auto-generated by src/db/start_db.sh"
    },
    {
      "id": "mt5_bridge",
      "name": "MT5 VPS mt5_bridge",
      "connectionString": "postgresql://postgres:postgres@127.0.0.1:5432/mt5_bridge",
      "note": "42Trade VPS bridge database"
    },
    {
      "id": "chronos",
      "name": "Chronos binance_trade",
      "connectionString": "postgresql://postgres:postgres@127.0.0.1:5432/binance_trade",
      "note": "ChronosTrade main database"
    },
    {
      "id": "external_signal",
      "name": "Chronos external_signal",
      "connectionString": "postgresql://postgres:postgres@127.0.0.1:5432/external_signal",
      "note": "ChronosTrade external signal database"
    }
  ]
}
EOF
  log "Wrote db-manager config to ${CONFIG_PATH}"
}

is_manager_running() {
  if [[ -f "${PID_PATH}" ]]; then
    local pid
    pid="$(cat "${PID_PATH}" 2>/dev/null || true)"
    if [[ -n "${pid}" ]] && kill -0 "${pid}" >/dev/null 2>&1; then
      return 0
    fi
  fi
  return 1
}

ensure_port_available() {
  local existing_pid
  existing_pid="$(lsof -ti tcp:"${DB_MANAGER_PORT}" -sTCP:LISTEN 2>/dev/null | head -n 1 || true)"
  if [[ -z "${existing_pid}" ]]; then
    return 0
  fi
  if [[ -f "${PID_PATH}" ]] && [[ "$(cat "${PID_PATH}" 2>/dev/null || true)" == "${existing_pid}" ]]; then
    return 0
  fi
  log "Port ${DB_MANAGER_PORT} is already in use by PID ${existing_pid}"
  exit 1
}

start_manager() {
  require_cmd node
  require_cmd python3
  ensure_port_available

  if is_manager_running; then
    local pid
    pid="$(cat "${PID_PATH}")"
    log "db-manager already running with PID ${pid}"
    return 0
  fi

  log "Starting db-manager on http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}"
  (
    cd "${DB_MANAGER_DIR}"
    export TRADING_DIR="${REPO_DIR}"
    export DB_MANAGER_CONFIG="${CONFIG_PATH}"
    export DB_MANAGER_HOST="${DB_MANAGER_HOST}"
    export DB_MANAGER_PORT="${DB_MANAGER_PORT}"
    export DB_MANAGER_LOG_PATH="${LOG_PATH}"
    export DB_MANAGER_PID_PATH="${PID_PATH}"
    python3 - <<PY
import os
import subprocess

env = os.environ.copy()
log_path = env["DB_MANAGER_LOG_PATH"]
pid_path = env["DB_MANAGER_PID_PATH"]

with open(log_path, "ab", buffering=0) as log:
    proc = subprocess.Popen(
        ["node", "server.js"],
        cwd=os.getcwd(),
        env=env,
        stdin=subprocess.DEVNULL,
        stdout=log,
        stderr=subprocess.STDOUT,
        start_new_session=True,
        close_fds=True,
    )
    with open(pid_path, "w", encoding="utf-8") as pid_file:
        pid_file.write(str(proc.pid))
PY
  )

  local attempts=10
  while (( attempts > 0 )); do
    if curl -fsS "http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}/api/connections" >/dev/null 2>&1; then
      log "db-manager started with PID $(cat "${PID_PATH}")"
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done

  if ! is_manager_running; then
    log "db-manager failed to start. Check ${LOG_PATH}"
    exit 1
  fi
  log "db-manager process started but health check did not pass. Check ${LOG_PATH}"
  exit 1
}

main() {
  ensure_postgres
  write_manager_config
  start_manager
  log "DB connection: postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  log "DB Manager URL: http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}"
  log "Access is restricted to localhost via host binding ${DB_MANAGER_HOST}"
}

main "$@"
