#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DB_MANAGER_DIR="${SCRIPT_DIR}/db-manager"
LOCAL_DIR="${SCRIPT_DIR}/.local/db-manager"
CONFIG_PATH="${LOCAL_DIR}/connections.json"
PID_PATH="${LOCAL_DIR}/db-manager.pid"
LOG_PATH="${LOCAL_DIR}/db-manager.log"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-mt5_bridge_local}"
DB_USER="${DB_USER:-$(id -un)}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_MANAGER_HOST="${DB_MANAGER_HOST:-127.0.0.1}"
DB_MANAGER_PORT="${DB_MANAGER_PORT:-8088}"

mkdir -p "${LOCAL_DIR}"

log() {
  printf '[start_db] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "Missing required command: $1"
    exit 1
  fi
}

choose_postgres_formula() {
  if ! command -v brew >/dev/null 2>&1; then
    return 1
  fi
  local running
  running="$(brew services list 2>/dev/null | awk '/^postgresql(@[0-9]+)?[[:space:]]/ { print $1; exit }')"
  if [[ -n "${running}" ]]; then
    printf '%s\n' "${running}"
    return 0
  fi
  local installed
  installed="$(brew list --formula 2>/dev/null | awk '/^postgresql(@[0-9]+)?$/ { print; exit }')"
  if [[ -n "${installed}" ]]; then
    printf '%s\n' "${installed}"
    return 0
  fi
  return 1
}

wait_for_postgres() {
  local attempts=20
  while (( attempts > 0 )); do
    if pg_isready -h "${DB_HOST}" -p "${DB_PORT}" >/dev/null 2>&1; then
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done
  return 1
}

ensure_postgres() {
  require_cmd pg_isready
  if pg_isready -h "${DB_HOST}" -p "${DB_PORT}" >/dev/null 2>&1; then
    log "Postgres already reachable at ${DB_HOST}:${DB_PORT}"
    return 0
  fi

  if ! command -v brew >/dev/null 2>&1; then
    log "Postgres is not reachable and Homebrew is unavailable."
    exit 1
  fi

  local formula
  formula="$(choose_postgres_formula || true)"
  if [[ -z "${formula}" ]]; then
    log "Could not find an installed Homebrew PostgreSQL formula."
    exit 1
  fi

  log "Starting Homebrew service: ${formula}"
  brew services start "${formula}" >/dev/null

  if ! wait_for_postgres; then
    log "Postgres did not become ready on ${DB_HOST}:${DB_PORT}"
    exit 1
  fi
  log "Postgres is ready at ${DB_HOST}:${DB_PORT}"
}

write_manager_config() {
  local conn
  if [[ -n "${DB_PASSWORD}" ]]; then
    conn="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  else
    conn="postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  fi

  cat > "${CONFIG_PATH}" <<EOF
{
  "connections": [
    {
      "id": "local",
      "name": "Local ${DB_NAME}",
      "connectionString": "${conn}",
      "note": "Auto-generated by db/start_db.sh"
    }
  ]
}
EOF
  log "Wrote db-manager config to ${CONFIG_PATH}"
}

is_manager_running() {
  if [[ -f "${PID_PATH}" ]]; then
    local pid
    pid="$(cat "${PID_PATH}" 2>/dev/null || true)"
    if [[ -n "${pid}" ]] && kill -0 "${pid}" >/dev/null 2>&1; then
      return 0
    fi
  fi
  return 1
}

ensure_port_available() {
  local existing_pid
  existing_pid="$(lsof -ti tcp:"${DB_MANAGER_PORT}" -sTCP:LISTEN 2>/dev/null | head -n 1 || true)"
  if [[ -z "${existing_pid}" ]]; then
    return 0
  fi
  if [[ -f "${PID_PATH}" ]] && [[ "$(cat "${PID_PATH}" 2>/dev/null || true)" == "${existing_pid}" ]]; then
    return 0
  fi
  log "Port ${DB_MANAGER_PORT} is already in use by PID ${existing_pid}"
  exit 1
}

start_manager() {
  require_cmd node
  ensure_port_available

  if is_manager_running; then
    local pid
    pid="$(cat "${PID_PATH}")"
    log "db-manager already running with PID ${pid}"
    return 0
  fi

  log "Starting db-manager on http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}"
  local cmd=(
    env
    "TRADING_DIR=${REPO_DIR}"
    "DB_MANAGER_CONFIG=${CONFIG_PATH}"
    "DB_MANAGER_HOST=${DB_MANAGER_HOST}"
    "DB_MANAGER_PORT=${DB_MANAGER_PORT}"
    node
    server.js
  )
  (
    cd "${DB_MANAGER_DIR}"
    if command -v setsid >/dev/null 2>&1; then
      nohup setsid "${cmd[@]}" >> "${LOG_PATH}" 2>&1 < /dev/null &
    else
      nohup "${cmd[@]}" >> "${LOG_PATH}" 2>&1 < /dev/null &
    fi
    echo $! > "${PID_PATH}"
  )

  local attempts=10
  while (( attempts > 0 )); do
    if curl -fsS "http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}/api/connections" >/dev/null 2>&1; then
      log "db-manager started with PID $(cat "${PID_PATH}")"
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done

  if ! is_manager_running; then
    log "db-manager failed to start. Check ${LOG_PATH}"
    exit 1
  fi
  log "db-manager process started but health check did not pass. Check ${LOG_PATH}"
  exit 1
}

main() {
  ensure_postgres
  write_manager_config
  start_manager
  log "DB connection: postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  log "DB Manager URL: http://${DB_MANAGER_HOST}:${DB_MANAGER_PORT}"
  log "Access is restricted to localhost via host binding ${DB_MANAGER_HOST}"
}

main "$@"
