"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const sharedRoot = path.join(repoRoot, "src", "shared");
const esbuild = require(path.join(repoRoot, "src", "admin", "node_modules", "esbuild"));

const ENTRY_POINTS = [
  "rules-engine/index.js",
  "rules-engine/ruleEngine.js",
  "rules-engine/predefinedRules.js",
  "rules-engine/features/detectArtifacts.js",
  "rules-engine/features/realtimeAnalysis.js",
  "rules-engine/features/strategyEventFunctions.js",
  "strategy-engine/index.js",
  "strategy-engine/strategyEngine.js",
  "utils/chartStrategyChecks.js",
  "utils/strategyScanEngine.js",
  "utils/suggestedTradeLevels.js",
];

const GENERATED_BANNER = [
  "\"use strict\";",
  "// Generated from the sibling ESM source by scripts/build_shared_cjs.cjs.",
  "// Do not edit this file directly; run `pnpm build:shared-cjs` from the repo root.",
  "",
].join("\n");

function normalizeNewlines(value = "") {
  return String(value).replace(/\r\n/g, "\n");
}

function buildSharedCjs(outdir) {
  esbuild.buildSync({
    entryPoints: ENTRY_POINTS.map((entry) => path.join(sharedRoot, entry)),
    outbase: sharedRoot,
    outdir,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node18",
    outExtension: { ".js": ".cjs" },
    banner: { js: GENERATED_BANNER.trimEnd() },
    legalComments: "none",
    logLevel: "silent",
  });
}

function generatedPathForEntry(outdir, entry) {
  return path.join(outdir, entry.replace(/\.js$/, ".cjs"));
}

function targetPathForEntry(entry) {
  return path.join(sharedRoot, entry.replace(/\.js$/, ".cjs"));
}

function copyGeneratedFiles(outdir) {
  for (const entry of ENTRY_POINTS) {
    const sourcePath = generatedPathForEntry(outdir, entry);
    const targetPath = targetPathForEntry(entry);
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.copyFileSync(sourcePath, targetPath);
  }
}

function checkGeneratedFiles(outdir) {
  const stale = [];
  for (const entry of ENTRY_POINTS) {
    const sourcePath = generatedPathForEntry(outdir, entry);
    const targetPath = targetPathForEntry(entry);
    const generated = normalizeNewlines(fs.readFileSync(sourcePath, "utf8"));
    const current = fs.existsSync(targetPath)
      ? normalizeNewlines(fs.readFileSync(targetPath, "utf8"))
      : "";
    if (generated !== current) {
      stale.push(path.relative(repoRoot, targetPath));
    }
  }
  return stale;
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "42trade-shared-cjs-"));
  try {
    buildSharedCjs(tempDir);
    if (checkOnly) {
      const stale = checkGeneratedFiles(tempDir);
      if (stale.length) {
        console.error("Shared CJS files are stale. Run `pnpm build:shared-cjs`.");
        for (const filePath of stale) console.error(`- ${filePath}`);
        process.exitCode = 1;
        return;
      }
      console.log("Shared CJS files are up to date.");
      return;
    }
    copyGeneratedFiles(tempDir);
    console.log(`Generated ${ENTRY_POINTS.length} shared CJS files.`);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  ENTRY_POINTS,
  buildSharedCjs,
  checkGeneratedFiles,
  generatedPathForEntry,
  targetPathForEntry,
};
